- docs/stm32-upgrade-pack/blackpill.md
Minor pic update highlighting exactly the problem with the blue board is in case someone get a red or other coloured board and isn't sure - hopefully this makes it super clear what to look out for.
> Highlight the problem with the blue expansion board

- docs/README.md
- docs/index.html
Changes:
- Added Ko-fi donate button
- Added page read progress bar
- Added "last updated" auto plugin
> updating docs

- docs/README.md
- docs/_sidebar.md
- docs/announcements/README.md
- docs/guides/README.md
- docs/index.html
> hopefully making things a bit clearer and cleaner

- docs/stm32-upgrade-pack/blackpill.md
New Component Housing schematic image
Changes: 
- noted optional connections/components
- Moved components around so component orientation matches how they're installed in the housing
- Added PSUs
- Added title/notes
> Housing schematic

- docs/stm32-upgrade-pack/blackpill.md
I think I've seen this question come up like, half a dozen times recently so figured it might be worth putting in the docs.
> Add picture & fix for the green board with the connected trace

- docs/README.md
Moved scales section, cleaned up some text and links, added link to Gaggiuino.HudsonCreativeGroup.com as that is live now
> Edit mfg partner

- docs/README.md
Removed the reference to the discord config bot as it is not used anymore.
> Removed reference to discord config bot

- docs/guides/3pln-stock-wiring-integration.md
> Forgot an important picture

- docs/guides-stm32/3pln-stock-wiring-integration.md
- docs/guides-stm32/lego-component-build-guide.md
> fix broken soldering link, fix wording on transducer tube fill instructions

- docs/README.md
- docs/_sidebar.md
- docs/accessories/hw-scales.md
- docs/accessories/tofnled.md
- docs/guides-stm32/lego-component-build-guide.md
Add ToFnLED, HW scales instructions
Fix multimeter check typo in the component build instructions
> Accessories

- docs/accessories/tofnled.md
Change Ali cable seller to one who uses correct terminology to reduce confusion for somelucky :)
> Change Ali cable seller (I2C for ToFnLED) to use correct terminology

- docs/announcements/README.md
Added a table with more Detailed info about EOL and recommendations about which version of the hardware to build.(i don't know the dates feel free to tell me and ill change them)  Also added a warning that's been echoed by multiple of the mods about current plans not being set in stone.
> EOL changes and reccomendation table

- docs/index.html
- docs/pcb/singleboard.md
- update flashing instructions for blackpill and nextion
- add gaggiuino site icon
- TODO: update lego build flashing guide. will do once review is done
> Update flashing instructions and add gaggiuino site icon

- docs/README.md
- docs/guides-stm32/3pln-custom-wiring.md
- docs/guides-stm32/3pln-stock-wiring-integration.md
- docs/guides-stm32/mcu-flashing.md
- docs/pcb/singleboard.md
> FIX: update nano release link, update BOM

- docs/index.html
With expansion of the docs having to find a small part to link to for example gets harder every day. Adding a full text search function makes this easier.
> Add full text search to sidebar

- docs/README.md
before expanding:
after expanding:
> Added image of the "avoid like the plague" machine in a dropdown

- docs/README.md
> updated feature comparison chart

- docs/README.md
- docs/_sidebar.md
- docs/guides-stm32/3pln-custom-wiring.md
- docs/guides-stm32/3pln-stock-wiring-integration.md
- docs/guides/interface-screen.md
> Add screen interface installation instructions

- docs/_sidebar.md
- docs/restore.html
> add static restore option

- docs/restore.html
- clarify about mixed-mode shit
> add mixed-mode warn, clarify when to download locally

- docs/_sidebar.md
Changed the URL of my store to the new domain espressio.shop
> Changed Espressio domain to new URL espressio.shop

- docs/guides-stm32/3pln-stock-wiring-integration.md
Resolve pr/165 - pr/167 merge conflict
> Resolve merge conflict
